### ISSUE TITLE
[Feature] Upgrade programing language to Java 17

### ISSUE THREAD

**Issue by wuchong** [alibaba/fluss#203]
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Motivation

Currently, the default programming language of Fluss is still Java 8. We would like to upgrade the programming language used in this project to Java 17. This upgrade will provide several benefits, including using the latest version of spotless, Google Java Format, and dependencies, and using new language features, and long-term support. 

However, we can't directly upgrade to Java 17, because most Flink users are still using Java 8 (Flink 2.0 turns to default Java 11), this requires Fluss release client/connector jars in Java 8 or Java 11 to be compatible with Flink. 

### Solution

Therefore, this is going to be a long work, and I would break it down into several phases:

## Phase 1
Upgrade the local development environment to Java 17, but still compile and release the project in Java 8. 

- [ ] CI build test on Java 8 with spotless skipped and compile checks on Java 17
- [ ] #114  (default local language to Java 17)

## Phase 2
Release for Java 8 & 11 & 17. 

- [ ] CI build test on Java 8 & 11 & 17 
- [ ] Release binary distribution for only Java 17
- [ ] Release maven artifacts for both Java 8 and Java 11 and Java 17

## Phase 3
Drop the legacy Java version support for Flink. Upgrade the language level to Java 17. 

- [ ] Remove CI build for Java 8 and Java 11

### Willingness to contribute

- [ ] I'm willing to submit a PR!

**Comment by psxjoy** [comment]
I think we should expedite the deprecation of JDK 8, given that Checkstyle only supports it up to version 9.6, with later versions requiring JDK 11 as the minimum（linked #220 ）.
Moreover, certain features are exclusively supported in JDK 11 and later.

我认为我们应该加快 JDK 8 的弃用，因为 Checkstyle 仅支持到 9.6 版本，而更高版本至少需要 JDK 11。
而且目前有些功能只有在jdk11中才有对应的特性。

**Comment by simonsssu** [comment]
Just one comment for phase-1,  some new features like Pattern Matching for switch in JDK17 may be involved in local dev environment while compile and release will fail with jdk8.

**Comment by Samrat002** [comment]
I'm curious why we shouldn't upgrade to Java 21 or higher?
If anyone had examined the effort estimate more closely previously, I'm not sure, looking for more context

**Comment by litiliu** [comment]
The flink 2.* is now using java 17 by default https://nightlies.apache.org/flink/flink-docs-stable/docs/deployment/java_compatibility/#java-17.  Looks like it's time to update the project to java 17?
